name: 'Ensure Package Builds'
on: [push, pull_request]

jobs:
  build:
    name: Ensure Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build