name: 'Tests'
on: [push, pull_request]

jobs:
  test:
    name: Run Tests on source code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x, 14.x]
        redis-version: [5]

    steps:
    - name: Git checkout
      uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start Redis v${{ matrix.redis-version }}
      uses: superchargejs/redis-github-action@1.1.0
      with:
        redis-version: ${{ matrix.redis-version }}

    - run: npm install
    - run: npm test